---
abstract: 'Extract Validation Rules from HTML Form'
author:
  - '=over 4'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::Differences: 0
  Test::More: 0.96
  Test::Name::FromLine: 0
  Test::Requires: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.04'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTML-ValidationRules
no_index:
  directory:
    - inc
    - t
    - xt
recommends:
  FormValidator::Lite: 0
  FormValidator::Simple: 0
requires:
  HTML::Parser: 0
  Scalar::Util::Numeric: 0
  autodie: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/kentaro/HTML-ValidationRules.git
version: 0.01
